Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -10,20 +10,54 @@ env:
 jobs:
   verify:
     runs-on: ubuntu-latest
+      steps:
+       - uses: actions/checkout@v3
+         - name: Get clean version
+           run: |
+            echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
+         - name: Get Description
+           run: |
+            echo description=$(grep "Description" mod.json) >> $GITHUB_ENV
+        - name: Check that version matches
+           run: |
+            if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./ -name mod.json))" != "${{ env.cleanVersion }}" ]]; then
+                echo "::debug::${{env.cleanVersion}}"
+                echo "::debug::$(cat $(find ./ -name mod.json ))"
+                echo "::error::Version in mod.json does not match tag version"
+                exit 1
+            fi
+  publish:
+    runs-on: ubuntu-latest
+    needs: verify
     steps:
-      - uses: actions/checkout@v3
-      - name: Get clean version
+      - name: Get clean version # Duplicating code is cool, actually
         run: |
           echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
-      - name: Get Description
-        run: |
-          echo description=$(grep "Description" mod.json) >> $GITHUB_ENV
-      - name: Check that version matches
-        run: |
-          if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./ -name mod.json))" != "${{ env.cleanVersion }}" ]]; then
-            echo "::debug::${{env.cleanVersion}}"
-            echo "::debug::$(cat $(find ./ -name mod.json ))"
-            echo "::error::Version in mod.json does not match tag version"
-            exit 1
-          fi
- 
+      - uses: actions/checkout@v3
+      - run: |
+          cat ${{ github.workspace }}/compressed/assets.tar.gz.* > ${{ github.workspace }}/compressed/assets.tar.gz # concat assets
+          tar -xvf ${{ github.workspace }}/compressed/assets.tar.gz # extract concatinated assets
+          rm -f ${{ github.workspace }}/compressed/assets.tar.gz* # delete assets
+          rm *.sh # Delete the asset splitting scripts
+      - name: Upload Thunderstore Package
+        uses: GreenTF/upload-thunderstore-package@v4
+        with:
+          community: northstar
+          # Name of the team to publish the mod under
+          # This should be modified if your github username is different than your team name on Thunderstore
+          namespace: ${{ github.repository_owner }}
+          # Name of the package
+          name: ${{ env.name }} # This can be modified if the package name differs from the repo name
+          # Package version to publish
+          version: ${{ env.cleanVersion }} # This is the tag that was created in the release but without the leading 'v'
+          # Description of the mod
+          description: ${{ env.description }}
+          # Thunderstore API token
+          token: ${{ secrets.TS_KEY }} 
+          # Directory to wrap the contents of the repo in
+          wrap: mods/${{ github.repository_owner }}.${{ env.name }} # This will wrap your Author.ModName folder in a mods/ folder before publishing
+          #deps: "northstar-Northstar@1.9.3" # <------------- Uncomment this line to add dependencies to your mod, each sparated by a space
+          repo: northstar.thunderstore.io
+          categories: |
+            mods
+            custom-menus
